### ISSUE TITLE
Idea: add unfreeze

### ISSUE THREAD

**Issue by ChillerDragon** [0xfaulty/maps#1]
![image](https://github.com/0xfaulty/maps/assets/20344300/c5dc60b8-3c33-4feb-9753-7a7bbaeee554)
![image](https://github.com/0xfaulty/maps/assets/20344300/3ef8010d-9d71-4d3a-b6a9-7ee11dd99965)
![image](https://github.com/0xfaulty/maps/assets/20344300/5c0da39a-e0a5-4b4c-8f54-55bfd752f69d)

**Comment by 0xfaulty** [comment]
![image](https://github.com/0xfaulty/maps/assets/22517228/490aff95-3206-4c23-b80b-8b581eb3c6f6)

**Comment by 0xfaulty** [comment]
when player fall down from right side, blocker trying to hook him as show with orange line

if I will add unfreeze, so will be hard to defense when several players just jump down (green line)

**Comment by ChillerDragon** [comment]
Hm yea good point. You can still lift them above the unfreeze but might be annoying yes agreed.
